2019-11-05 20:25:59,771 - logger.py[line:59] - INFO: Time Tag: 2019-11-05_202559
2019-11-05 20:25:59,811 - __init__.py[line:505] - WARNING: Setting up a new session...
2019-11-05 20:25:59,814 - torch_visdom.py[line:190] - ERROR: Error connecting to Visdom server
2019-11-05 20:25:59,815 - torch_visdom.py[line:192] - INFO: Visdom is not installed, but no server connection. The visual data is stored locally.
2019-11-05 20:25:59,815 - manager.py[line:47] - INFO: Device: pc
2019-11-05 20:25:59,815 - manager.py[line:48] - INFO: -----------------------Set Seed None------------------------
2019-11-05 20:25:59,815 - manager.py[line:58] - INFO: ----------------------Set Dataset MOT-----------------------
2019-11-05 20:25:59,815 - manager.py[line:117] - INFO: Set Split ID  0
2019-11-05 20:25:59,815 - solverbase.py[line:17] - INFO: Instance num [ 3] Sample num [ 2] Depth [ 2]
2019-11-05 20:25:59,816 - __init__.py[line:53] - ERROR: No this dataset. Wrong name.
